version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: million-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: milliondb
    volumes:
      - mongo-data:/data/db
      - ./seed:/docker-entrypoint-initdb.d
    networks:
      - million-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: million-api
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=milliondb
    depends_on:
      - mongodb
    networks:
      - million-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: million-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
    depends_on:
      - api
    networks:
      - million-network

volumes:
  mongo-data:

networks:
  million-network:
    driver: bridge
